CREATE TABLE "acquereur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "acquereur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text,
	"civilite_id" integer,
	"patronyme" text,
	"prenom" text,
	"civilite2_id" integer,
	"patronyme2" text,
	"prenom2" text,
	"civilite3_id" integer,
	"patronyme3" text,
	"prenom3" text,
	"nom_complet" text,
	"rs" text,
	"nature_juridique_id" integer,
	"telephone" text,
	"portable" text,
	"email" text,
	"email2" text,
	"adresse_actuelle" text,
	"cp_actuel" text,
	"commune_actuelle" text,
	"commune_origine" text,
	"date_modif_adresse" timestamp,
	"type_logement_actuel_id" integer,
	"situation_familiale_id" integer,
	"situation_famille_id" integer,
	"type_menage_id" integer,
	"adulte1_age" integer,
	"adulte2_age" integer,
	"adulte1_date_naissance" timestamp,
	"adulte2_date_naissance" timestamp,
	"adulte1_lieu_naissance" text,
	"adulte2_lieu_naissance" text,
	"adulte1_csp_id" integer,
	"adulte2_csp_id" integer,
	"adulte1_metier" text,
	"adulte2_metier" text,
	"adulte1_commune_travail" text,
	"adulte2_commune_travail" text,
	"age_enfant1" integer,
	"age_enfant2" integer,
	"age_enfant3" integer,
	"age_enfant4" integer,
	"age_enfant5" integer,
	"nombre_adultes" integer,
	"nombre_enfants" integer,
	"enfant_a_venir" integer,
	"tranche_age_id" integer,
	"plafond_ressources_id" integer,
	"revenu_quartile_id" integer,
	"revenus_foyer_fiscal" numeric,
	"annee_declaration" integer,
	"revenus_net_imposable_nm1" numeric,
	"revenu_net_foyer_mensuel" numeric,
	"pension_autres_revenus" numeric,
	"loyer_actuel" numeric,
	"prix_achat" numeric,
	"taux_tva" real,
	"apport_reel_hors_subvention" numeric,
	"subvention" numeric,
	"est_ptz" boolean,
	"multi_accedant" boolean,
	"mensualite_financement" numeric,
	"taux_effort" real,
	"duree_financement_mois" integer,
	"conseiller_commercial_id" integer,
	"info_pour_entreprise" text,
	"commentaire" text,
	"date_creation" timestamp,
	"date_modification" timestamp
);
--> statement-breakpoint
CREATE TABLE "acquereur_plafond_ressources" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "acquereur_plafond_ressources_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "acquereur_revenu_quartile" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "acquereur_revenu_quartile_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"borne_max" integer
);
--> statement-breakpoint
CREATE TABLE "acquereur_tranche_age" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "acquereur_tranche_age_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"borne_max" integer
);
--> statement-breakpoint
CREATE TABLE "banque_courtage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banque_courtage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "civilite" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "civilite_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"libelle_court" text
);
--> statement-breakpoint
CREATE TABLE "comm_vendeur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "comm_vendeur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"commercialisation_id" integer,
	"lot_id" integer,
	"commercial_id" integer,
	"pourcentage" real,
	"evenement" integer,
	"tx_comm_vendeur" real,
	"mnt_comm_vendeur" numeric,
	"date_reglement" timestamp,
	"date_validation" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "commercial" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "commercial_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"denomination" text,
	"prenom" text,
	"initiales" text,
	"email" text,
	"societe" text,
	"fonction" text
);
--> statement-breakpoint
CREATE TABLE "commercialisation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "commercialisation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lot_id" integer NOT NULL,
	"acquereur_id" integer,
	"type_acquereur_id" integer,
	"nature_achat_id" integer,
	"fiscalite_acquereur_id" integer,
	"moyen_paiement_id" integer,
	"banque_courtage_id" integer,
	"date_resa" timestamp,
	"date_prevue_signature_acte" timestamp,
	"date_signature_acte_vefa" timestamp,
	"date_signature_contrat_loc" timestamp,
	"date_resiliation_contrat_loc" timestamp,
	"date_levee_option" timestamp,
	"date_livraison" timestamp,
	"date_annulation" timestamp,
	"motif_annulation" text,
	"annulation_commentaire" text,
	"date_previ_actabilite" timestamp,
	"prix_vente_reel_ttc" numeric,
	"prix_vente_reel_ht" numeric,
	"taux_tva_reel" real,
	"remise_client_ttc" numeric,
	"montant_depot_garantie" real,
	"taux_comm_resa" real,
	"taux_comm_acte" real,
	"comm_vendeur_a_verser_resa" numeric,
	"comm_vendeur_a_verser_acte" numeric,
	"est_fiscalite" boolean,
	"comm_fisca" text,
	"est_justif_fiscal" boolean,
	"loyer" numeric,
	"epargne" numeric,
	"pas_aide_rm" boolean,
	"montant_subv" numeric,
	"montant_subv_acpte" numeric,
	"solde_demande" boolean,
	"avec_honoraire_courtage" boolean,
	"montant_hono_courtage_client" numeric,
	"montant_hono_courtage_banque" numeric,
	"avec_souscription_capital_kpi" boolean,
	"pas_de_souscription_capital" boolean,
	"date_souscription" timestamp,
	"commentaires_souscription" text,
	"avec_clause_particuliere" integer,
	"motif_clause_particuliere_id" integer,
	"commentaire_clause_particuliere" text,
	"avec_tma" boolean,
	"tma_montant_ouverture_dossier" numeric,
	"tma_date_envoi_courrier" timestamp,
	"tma_date_paiement_solde" timestamp,
	"tma_pmr_montant" numeric,
	"tma_pmr_contrat_signe" boolean,
	"tma_pmr_date_remis_notaire" timestamp,
	"tma_commentaire" text,
	"courrier_info_demarrage_date_envoi" timestamp,
	"plan_technique_date_envoi" timestamp,
	"choix_materiaux_date_envoi" timestamp,
	"choix_materiaux_date_valide" timestamp,
	"placo_date_envoi" timestamp,
	"placo_rdv_date" timestamp,
	"placo_rdv_heure" timestamp,
	"trois_mois_avant_livraison_date_envoi" timestamp,
	"trois_mois_avant_livraison_periode" text,
	"livraison_date_envoi_courrier" timestamp,
	"livraison_rdv_date" timestamp,
	"livraison_rdv_heure" timestamp,
	"livraison_trimestre_prevu_contrat" text,
	"livraison_trimestre_decale" text,
	"date_etat_sortie_lieux" timestamp,
	"date_demande_agrement" timestamp,
	"date_agrement_obtenu" timestamp,
	"date_reception_courrier_lvo" timestamp,
	"est_revente_bien" integer,
	"date_butoir_revente" timestamp,
	"cdv_technique" text,
	"cdv_promo" text
);
--> statement-breakpoint
CREATE TABLE "concept" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "concept_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "csp" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "csp_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"numero" integer,
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "destination" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "destination_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"libelle_comm" text,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "fiscalite_acquereur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fiscalite_acquereur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"libelle_court" text
);
--> statement-breakpoint
CREATE TABLE "lot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"destination_id" integer,
	"num_lot" text,
	"lot_associe" text,
	"famille_de_bien" text,
	"type_de_bien" text,
	"designation" text,
	"adresse" text,
	"num_etage" text,
	"exposition" text,
	"num_parcelle" text,
	"num_copropriete" text,
	"tantiemes" real,
	"est_partie_commune" boolean,
	"est_vente_acheve" boolean,
	"surf_habitable" real,
	"surface_utile" real,
	"surf_terrasse" real,
	"surf_garage" real,
	"surf_cave" real,
	"surf_balcon" real,
	"surf_loggias" real,
	"surf_remise" real,
	"surf_jardin" real,
	"surf_terrain" real,
	"prix_origine" numeric,
	"prix_vente_ht" numeric,
	"prix_vente_ttc" numeric,
	"tva" text,
	"prix_m2" numeric,
	"montant_hono_com" numeric,
	"commercial_id" integer,
	"acquereur_id" integer,
	"taux_comm_resa" real,
	"taux_comm_acte" real,
	"comm_vendeur_a_verser_resa" numeric,
	"comm_vendeur_a_verser_acte" numeric,
	"locataire_civilite" text,
	"locataire_patronyme" text,
	"locataire_prenom" text,
	"locataire_telephone" text,
	"locataire_portable" text,
	"pdl" text,
	"pce" text,
	"date_livraison_sccv" timestamp,
	"commentaire" text,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "motif_clause_particuliere" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "motif_clause_particuliere_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "moyen_paiement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "moyen_paiement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "nature_achat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nature_achat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"libelle_long" text,
	"ordre_comm" integer
);
--> statement-breakpoint
CREATE TABLE "nature_juridique" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "nature_juridique_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "operation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "operation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer,
	"libelle" text NOT NULL,
	"adresse" text,
	"cp" text,
	"commune" text,
	"nom_zac" text,
	"secteur_geographique_id" integer,
	"sur_rennes_metropole" boolean,
	"anru" boolean,
	"anru_commentaire" text,
	"indiv_coll" integer,
	"annee_dgd" integer,
	"abreviation_code_reserve" text,
	"possibilite_investisseur" boolean,
	"taux_investisseur_autorise" real,
	"commentaire_investisseur" text,
	"date_validation_engagement" timestamp,
	"date_abandon" timestamp,
	"commentaires_abandon" text,
	"masquer_commercial" boolean,
	"masquer_comptable" boolean,
	"masquer_promo" boolean,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "secteur_geographique" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "secteur_geographique_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "situation_familiale" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "situation_familiale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "situation_famille" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "situation_famille_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "structure_juridique" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "structure_juridique_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rs" text NOT NULL,
	"num_tva_intra" text,
	"siret" text,
	"date_debut_activite" timestamp,
	"date_immat" timestamp,
	"date_liquidation" timestamp,
	"capital" integer,
	"nb_part" integer,
	"montant_part" integer,
	"sccv_hf" boolean,
	"sccv_hlm" boolean
);
--> statement-breakpoint
CREATE TABLE "tma" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tma_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"commercialisation_id" integer NOT NULL,
	"ref_devis" text,
	"date_devis" timestamp,
	"objet_devis" text,
	"date_signature_devis" timestamp,
	"montant_devis" numeric,
	"montant_versement1" numeric,
	"montant_versement2" numeric,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "tranche" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tranche_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operation_id" integer NOT NULL,
	"libelle" text,
	"concept_id" integer,
	"adresse" text,
	"nb_logt_indiv" integer,
	"nb_logt_coll" integer,
	"nb_autres_locaux" integer,
	"nb_terrain" integer,
	"dont_logt_coll_psla" integer,
	"dont_logt_indiv_psla" integer,
	"dont_logt_coll_brs" integer,
	"dont_logt_indiv_brs" integer,
	"nb_etage" integer,
	"duree_chantier_mois" integer,
	"date_convention" timestamp,
	"date_livraison_contractuelle" timestamp,
	"pas_de_commercialisation" boolean,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "type_acquereur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_acquereur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "type_logement_actuel" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_logement_actuel_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"num_rm" integer
);
--> statement-breakpoint
CREATE TABLE "type_menage" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_menage_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "versement_depot_garantie" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "versement_depot_garantie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"commercialisation_id" integer NOT NULL,
	"montant_verse" real,
	"date_remise" timestamp,
	"date_creation" timestamp,
	"commentaire" text
);
--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_civilite_id_civilite_id_fk" FOREIGN KEY ("civilite_id") REFERENCES "public"."civilite"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_civilite2_id_civilite_id_fk" FOREIGN KEY ("civilite2_id") REFERENCES "public"."civilite"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_civilite3_id_civilite_id_fk" FOREIGN KEY ("civilite3_id") REFERENCES "public"."civilite"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_nature_juridique_id_nature_juridique_id_fk" FOREIGN KEY ("nature_juridique_id") REFERENCES "public"."nature_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_type_logement_actuel_id_type_logement_actuel_id_fk" FOREIGN KEY ("type_logement_actuel_id") REFERENCES "public"."type_logement_actuel"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_situation_familiale_id_situation_familiale_id_fk" FOREIGN KEY ("situation_familiale_id") REFERENCES "public"."situation_familiale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_situation_famille_id_situation_famille_id_fk" FOREIGN KEY ("situation_famille_id") REFERENCES "public"."situation_famille"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_type_menage_id_type_menage_id_fk" FOREIGN KEY ("type_menage_id") REFERENCES "public"."type_menage"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_adulte1_csp_id_csp_id_fk" FOREIGN KEY ("adulte1_csp_id") REFERENCES "public"."csp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_adulte2_csp_id_csp_id_fk" FOREIGN KEY ("adulte2_csp_id") REFERENCES "public"."csp"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_tranche_age_id_acquereur_tranche_age_id_fk" FOREIGN KEY ("tranche_age_id") REFERENCES "public"."acquereur_tranche_age"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_plafond_ressources_id_acquereur_plafond_ressources_id_fk" FOREIGN KEY ("plafond_ressources_id") REFERENCES "public"."acquereur_plafond_ressources"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_revenu_quartile_id_acquereur_revenu_quartile_id_fk" FOREIGN KEY ("revenu_quartile_id") REFERENCES "public"."acquereur_revenu_quartile"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "acquereur" ADD CONSTRAINT "acquereur_conseiller_commercial_id_commercial_id_fk" FOREIGN KEY ("conseiller_commercial_id") REFERENCES "public"."commercial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comm_vendeur" ADD CONSTRAINT "comm_vendeur_commercialisation_id_commercialisation_id_fk" FOREIGN KEY ("commercialisation_id") REFERENCES "public"."commercialisation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comm_vendeur" ADD CONSTRAINT "comm_vendeur_lot_id_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "comm_vendeur" ADD CONSTRAINT "comm_vendeur_commercial_id_commercial_id_fk" FOREIGN KEY ("commercial_id") REFERENCES "public"."commercial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_lot_id_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_acquereur_id_acquereur_id_fk" FOREIGN KEY ("acquereur_id") REFERENCES "public"."acquereur"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_type_acquereur_id_type_acquereur_id_fk" FOREIGN KEY ("type_acquereur_id") REFERENCES "public"."type_acquereur"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_nature_achat_id_nature_achat_id_fk" FOREIGN KEY ("nature_achat_id") REFERENCES "public"."nature_achat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_fiscalite_acquereur_id_fiscalite_acquereur_id_fk" FOREIGN KEY ("fiscalite_acquereur_id") REFERENCES "public"."fiscalite_acquereur"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_moyen_paiement_id_moyen_paiement_id_fk" FOREIGN KEY ("moyen_paiement_id") REFERENCES "public"."moyen_paiement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_banque_courtage_id_banque_courtage_id_fk" FOREIGN KEY ("banque_courtage_id") REFERENCES "public"."banque_courtage"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_motif_clause_particuliere_id_motif_clause_particuliere_id_fk" FOREIGN KEY ("motif_clause_particuliere_id") REFERENCES "public"."motif_clause_particuliere"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lot" ADD CONSTRAINT "lot_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lot" ADD CONSTRAINT "lot_destination_id_destination_id_fk" FOREIGN KEY ("destination_id") REFERENCES "public"."destination"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lot" ADD CONSTRAINT "lot_commercial_id_commercial_id_fk" FOREIGN KEY ("commercial_id") REFERENCES "public"."commercial"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lot" ADD CONSTRAINT "lot_acquereur_id_acquereur_id_fk" FOREIGN KEY ("acquereur_id") REFERENCES "public"."acquereur"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_secteur_geographique_id_secteur_geographique_id_fk" FOREIGN KEY ("secteur_geographique_id") REFERENCES "public"."secteur_geographique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tma" ADD CONSTRAINT "tma_commercialisation_id_commercialisation_id_fk" FOREIGN KEY ("commercialisation_id") REFERENCES "public"."commercialisation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_operation_id_operation_id_fk" FOREIGN KEY ("operation_id") REFERENCES "public"."operation"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_concept_id_concept_id_fk" FOREIGN KEY ("concept_id") REFERENCES "public"."concept"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "versement_depot_garantie" ADD CONSTRAINT "versement_depot_garantie_commercialisation_id_commercialisation_id_fk" FOREIGN KEY ("commercialisation_id") REFERENCES "public"."commercialisation"("id") ON DELETE no action ON UPDATE no action;