CREATE TABLE "situation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "situation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "stade_com" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "situation_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "situation_depuis_le" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_situation_id_situation_id_fk" FOREIGN KEY ("situation_id") REFERENCES "public"."situation"("id") ON DELETE no action ON UPDATE no action;