CREATE TABLE "architecte" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "architecte_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rs" text NOT NULL,
	"commune" text,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "etude_notaire" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "etude_notaire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nom_etude" text NOT NULL,
	"adresse" text,
	"cp" text,
	"commune" text,
	"email" text,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "fonction_interlocuteur_notaire" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fonction_interlocuteur_notaire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "interlocuteur_notaire" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "interlocuteur_notaire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"etude_notaire_id" integer,
	"fonction_id" integer,
	"civilite" text,
	"patronyme" text,
	"prenom" text,
	"telephone" text,
	"email" text
);
--> statement-breakpoint
ALTER TABLE "commercialisation" ADD COLUMN "date_signature_comm" text;--> statement-breakpoint
ALTER TABLE "operation" ADD COLUMN "notaire_vente_id" integer;--> statement-breakpoint
ALTER TABLE "operation" ADD COLUMN "clerc_vente_id" integer;--> statement-breakpoint
ALTER TABLE "operation" ADD COLUMN "notaire_foncier_id" integer;--> statement-breakpoint
ALTER TABLE "operation" ADD COLUMN "clerc_foncier_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "architecte_mandataire_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "architecte_cotraitant_id" integer;--> statement-breakpoint
ALTER TABLE "interlocuteur_notaire" ADD CONSTRAINT "interlocuteur_notaire_etude_notaire_id_etude_notaire_id_fk" FOREIGN KEY ("etude_notaire_id") REFERENCES "public"."etude_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interlocuteur_notaire" ADD CONSTRAINT "interlocuteur_notaire_fonction_id_fonction_interlocuteur_notaire_id_fk" FOREIGN KEY ("fonction_id") REFERENCES "public"."fonction_interlocuteur_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_notaire_vente_id_interlocuteur_notaire_id_fk" FOREIGN KEY ("notaire_vente_id") REFERENCES "public"."interlocuteur_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_clerc_vente_id_interlocuteur_notaire_id_fk" FOREIGN KEY ("clerc_vente_id") REFERENCES "public"."interlocuteur_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_notaire_foncier_id_interlocuteur_notaire_id_fk" FOREIGN KEY ("notaire_foncier_id") REFERENCES "public"."interlocuteur_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "operation" ADD CONSTRAINT "operation_clerc_foncier_id_interlocuteur_notaire_id_fk" FOREIGN KEY ("clerc_foncier_id") REFERENCES "public"."interlocuteur_notaire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_architecte_mandataire_id_architecte_id_fk" FOREIGN KEY ("architecte_mandataire_id") REFERENCES "public"."architecte"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_architecte_cotraitant_id_architecte_id_fk" FOREIGN KEY ("architecte_cotraitant_id") REFERENCES "public"."architecte"("id") ON DELETE no action ON UPDATE no action;