CREATE TABLE "categorie_subvention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categorie_subvention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "certification" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "certification_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "label" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "label_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "liste_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "liste_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"domaine" text,
	"code" text,
	"libelle" text NOT NULL,
	"ordre" integer
);
--> statement-breakpoint
CREATE TABLE "ofs_nom" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ofs_nom_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organisme_subvention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organisme_subvention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "performance_energetique" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "performance_energetique_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "signataire" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "signataire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "stade_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stade_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"liste_avancement_id" integer,
	"date_previ_compta_debut_annee" timestamp,
	"date_previ_maj_promo" timestamp,
	"date_reelle" timestamp,
	"ordre" integer,
	"pourcentage_avancement_reel" real,
	"montant_previ" numeric,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "subvention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "subvention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"categorie_id" integer,
	"organisme_id" integer,
	"num_convention" text,
	"date_convention" timestamp,
	"date_caducite" timestamp,
	"montant_agrement" numeric,
	"montant_provisoire" numeric,
	"montant_definitif" numeric,
	"budget_previ_montant" numeric,
	"budget_previ_commentaire" text,
	"fin_de_suivi" boolean,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "type_mission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_mission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_montant_ht" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_montant_ttc" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_pourc_acpte_prevu" real;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_acompte" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_signataire_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "ofs_nom_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_montant_ht" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_acpte_pourc_prevu" real;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_acpte_montant_verse" real;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_signataire_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_compromis_date_previ" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_ofs_compromis_date_reelle" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_bail_operateur_date_previ" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "terrain_bail_operateur_date_reelle" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "autre_montant" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "autre_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "certification_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "label_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "performance_energetique_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "est_moe_interne" boolean;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "mission_moe_interne_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "commentaire_avancement" text;--> statement-breakpoint
ALTER TABLE "stade_avancement" ADD CONSTRAINT "stade_avancement_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "stade_avancement" ADD CONSTRAINT "stade_avancement_liste_avancement_id_liste_avancement_id_fk" FOREIGN KEY ("liste_avancement_id") REFERENCES "public"."liste_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subvention" ADD CONSTRAINT "subvention_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subvention" ADD CONSTRAINT "subvention_categorie_id_categorie_subvention_id_fk" FOREIGN KEY ("categorie_id") REFERENCES "public"."categorie_subvention"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subvention" ADD CONSTRAINT "subvention_organisme_id_organisme_subvention_id_fk" FOREIGN KEY ("organisme_id") REFERENCES "public"."organisme_subvention"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_terrain_signataire_id_signataire_id_fk" FOREIGN KEY ("terrain_signataire_id") REFERENCES "public"."signataire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_ofs_nom_id_ofs_nom_id_fk" FOREIGN KEY ("ofs_nom_id") REFERENCES "public"."ofs_nom"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_terrain_ofs_signataire_id_signataire_id_fk" FOREIGN KEY ("terrain_ofs_signataire_id") REFERENCES "public"."signataire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_certification_id_certification_id_fk" FOREIGN KEY ("certification_id") REFERENCES "public"."certification"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_label_id_label_id_fk" FOREIGN KEY ("label_id") REFERENCES "public"."label"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_performance_energetique_id_performance_energetique_id_fk" FOREIGN KEY ("performance_energetique_id") REFERENCES "public"."performance_energetique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_mission_moe_interne_id_type_mission_id_fk" FOREIGN KEY ("mission_moe_interne_id") REFERENCES "public"."type_mission"("id") ON DELETE no action ON UPDATE no action;