CREATE TABLE "mission_moe_interne" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mission_moe_interne_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_mission_moe_interne_id_mission_moe_interne_id_fk" FOREIGN KEY ("mission_moe_interne_id") REFERENCES "public"."mission_moe_interne"("id") ON DELETE no action ON UPDATE no action;