CREATE TABLE "associe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "associe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rs" text NOT NULL,
	"forme_juridique" text,
	"siren" text,
	"adresse1" text,
	"adresse2" text,
	"cp" text,
	"commune" text,
	"tel" text,
	"est_hlm" boolean,
	"contact_nom_complet" text,
	"contact_fonction" text,
	"email" text,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "banque" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banque_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"cc_nom" text,
	"cc_adresse" text,
	"cc_cp" text,
	"cc_commune" text,
	"cc_tel" text,
	"cc_email" text,
	"pret_nom" text,
	"pret_adresse" text,
	"pret_cp" text,
	"pret_commune" text,
	"pret_tel" text,
	"pret_email" text
);
--> statement-breakpoint
CREATE TABLE "compte_banque" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "compte_banque_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer NOT NULL,
	"banque_id" integer,
	"type_compte_banque_id" integer,
	"utilisation_compte_id" integer,
	"num_compte" text,
	"iban" text,
	"bic" text,
	"est_cloture" boolean,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "gestionnaire_sccv" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gestionnaire_sccv_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "index_taux" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "index_taux_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "motif_remuneration_associe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "motif_remuneration_associe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "partenariat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "partenariat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "participation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "participation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer NOT NULL,
	"associe_id" integer,
	"pourcentage" real,
	"commentaires" text,
	"conv_treso" boolean,
	"motif_remuneration_associe_id" integer,
	"date_signature_conv" timestamp,
	"date_application" timestamp,
	"date_fin_remuneration" timestamp,
	"index_taux_remuneration_id" integer,
	"info_taux_remuneration" text,
	"periodicite_versement" text
);
--> statement-breakpoint
CREATE TABLE "personne" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "personne_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"patronyme" text,
	"prenom" text,
	"est_present" boolean,
	"fonction_id" integer,
	"equipe_personne_id" integer,
	"email" text
);
--> statement-breakpoint
CREATE TABLE "sie" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sie_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"adresse" text,
	"cp" text,
	"commune" text
);
--> statement-breakpoint
CREATE TABLE "structure_juridique_stade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "structure_juridique_stade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "type_compte_banque" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_compte_banque_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "utilisation_compte" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "utilisation_compte_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "stade_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "personne_comptable_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "gestionnaire_sccv_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "partenariat_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "hfsga" boolean;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_bilan_debut_premier_exercice" timestamp;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_bilan_fin_premier_exercice" timestamp;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_modif_cloture" text;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_planning_cloture" text;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_liberation_capital" timestamp;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "edi_tva" boolean;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "edi_liasse" boolean;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "cpte_fiscal" boolean;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "sie_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "civilite_id" integer;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "interlocuteur_sie" text;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD COLUMN "date_mandat_sie" timestamp;--> statement-breakpoint
ALTER TABLE "compte_banque" ADD CONSTRAINT "compte_banque_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compte_banque" ADD CONSTRAINT "compte_banque_banque_id_banque_id_fk" FOREIGN KEY ("banque_id") REFERENCES "public"."banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compte_banque" ADD CONSTRAINT "compte_banque_type_compte_banque_id_type_compte_banque_id_fk" FOREIGN KEY ("type_compte_banque_id") REFERENCES "public"."type_compte_banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "compte_banque" ADD CONSTRAINT "compte_banque_utilisation_compte_id_utilisation_compte_id_fk" FOREIGN KEY ("utilisation_compte_id") REFERENCES "public"."utilisation_compte"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participation" ADD CONSTRAINT "participation_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participation" ADD CONSTRAINT "participation_associe_id_associe_id_fk" FOREIGN KEY ("associe_id") REFERENCES "public"."associe"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participation" ADD CONSTRAINT "participation_motif_remuneration_associe_id_motif_remuneration_associe_id_fk" FOREIGN KEY ("motif_remuneration_associe_id") REFERENCES "public"."motif_remuneration_associe"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "participation" ADD CONSTRAINT "participation_index_taux_remuneration_id_index_taux_id_fk" FOREIGN KEY ("index_taux_remuneration_id") REFERENCES "public"."index_taux"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_stade_id_structure_juridique_stade_id_fk" FOREIGN KEY ("stade_id") REFERENCES "public"."structure_juridique_stade"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_personne_comptable_id_personne_id_fk" FOREIGN KEY ("personne_comptable_id") REFERENCES "public"."personne"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_gestionnaire_sccv_id_gestionnaire_sccv_id_fk" FOREIGN KEY ("gestionnaire_sccv_id") REFERENCES "public"."gestionnaire_sccv"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_partenariat_id_partenariat_id_fk" FOREIGN KEY ("partenariat_id") REFERENCES "public"."partenariat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_sie_id_sie_id_fk" FOREIGN KEY ("sie_id") REFERENCES "public"."sie"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "structure_juridique" ADD CONSTRAINT "structure_juridique_civilite_id_civilite_id_fk" FOREIGN KEY ("civilite_id") REFERENCES "public"."civilite"("id") ON DELETE no action ON UPDATE no action;