CREATE TABLE "action_alerte" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "action_alerte_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "action_fin_gfa_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "action_fin_gfa_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "banque_action_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "banque_action_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "budget" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "budget_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"liste_budget_id" integer,
	"date_validation" timestamp,
	"date_saisie_promoges" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "categorie_frais" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categorie_frais_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"est_publicite" boolean,
	"ordre" integer,
	"usage_frais_id" integer
);
--> statement-breakpoint
CREATE TABLE "deblocage_psla" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deblocage_psla_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"financement_id" integer,
	"psla_id" integer,
	"numero" integer,
	"montant" numeric,
	"date_demande" timestamp,
	"date_versement" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "deblocage_subvention" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "deblocage_subvention_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"subvention_id" integer,
	"date_demande" timestamp,
	"montant" numeric,
	"date_paiement" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "fin_pret" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fin_pret_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "financement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "financement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"type_financement_id" integer,
	"banque_id" integer,
	"sur_ope" boolean,
	"montant_financement" numeric,
	"montant_previ" numeric,
	"infos_pret_previ" text,
	"date_envoi_dossier" timestamp,
	"date_signature" timestamp,
	"date_butoir" timestamp,
	"action_alerte_id" integer,
	"date_debut_mobilisation" timestamp,
	"date_fin_mobilisation" timestamp,
	"duree_mois_mob_psla" integer,
	"fin_pret_id" integer,
	"index_taux_id" integer,
	"index_taux_floore" boolean,
	"marge_banque" real,
	"taux_pret" real,
	"periodicite" text,
	"commission_engagement_pourc" real,
	"frais_dossier" numeric,
	"est_prlv_frais_dossier" boolean,
	"est_phase_amortissement" boolean,
	"est_solde" boolean,
	"num_contrat" text,
	"part_sociale_montant" numeric,
	"statut_part_sociale_id" integer,
	"date_statut_part_sociale" timestamp,
	"apport_promoteur" numeric,
	"statut_apport_id" integer,
	"blocage_hono_oc_montant" numeric,
	"blocage_hono_oc_fin" text,
	"blocage_hono_oc_comment" text,
	"est_hf_caution_oc" boolean,
	"mandat_hypothequer_id" integer,
	"mandat_cout_montant" numeric,
	"statut_cout_mandat_id" integer,
	"prev_mt_oc" integer,
	"contrat_montant" numeric,
	"contrat_nb_logt" integer,
	"date_debut_echeance" timestamp,
	"date_fin_echeance" timestamp,
	"montant_echeance" numeric,
	"date_verst_pret" timestamp,
	"pret_employeur_numero_modif_echeance" integer,
	"pret_employeur_date_debut_amort" timestamp,
	"est_amort_differe" boolean,
	"amortissement_differe_duree" real,
	"amortissement_differe_fin_date" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "frais_financier" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "frais_financier_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"categorie_frais_id" integer,
	"budget_montant" numeric,
	"actua_montant" numeric,
	"consomme_montant" numeric,
	"reel_montant" numeric,
	"ordre" integer
);
--> statement-breakpoint
CREATE TABLE "garantie_emprunt_action_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "garantie_emprunt_action_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "gfa" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gfa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"sur_ope" boolean,
	"banque_id" integer,
	"est_intrinseque" boolean,
	"date_validation" timestamp,
	"date_dossier" timestamp,
	"date_accord" timestamp,
	"date_attestation" timestamp,
	"apport_promoteur" numeric,
	"statut_apport_promoteur_gfa_id" integer,
	"action_fin_date" timestamp,
	"action_fin_type_id" integer,
	"fin_gfa" boolean,
	"fonds_garantie_montant" numeric,
	"fonds_garantie_date_demande_remb" timestamp,
	"fonds_garantie_date_remb" timestamp,
	"part_sociale_montant" numeric,
	"part_sociale_date_demande_remb" timestamp,
	"part_sociale_date_remb" timestamp,
	"part_sociale_commentaire" text,
	"hf_caution" boolean,
	"taux" real,
	"periode_taux_gfa_id" integer,
	"duree_mois" integer,
	"commentaire_taux" text,
	"base_initiale" numeric,
	"commission_caution_montant" numeric,
	"date_premier_prlvt" timestamp,
	"frais_dossier" numeric,
	"precom_pourc" real,
	"ca_ttc_min" numeric,
	"commentaire_conditions" text,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "liste_budget" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "liste_budget_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mandat_hypothequer" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mandat_hypothequer_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "mode_repart_quote_part" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mode_repart_quote_part_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organisme_agrement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organisme_agrement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "organisme_garantie_emprunt" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "organisme_garantie_emprunt_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "periode_taux_gfa" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "periode_taux_gfa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "psla" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "psla_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer,
	"estim_psla" integer,
	"montant_psla" numeric,
	"cout_total" numeric,
	"nb_logt_agrement" integer,
	"num_agrement" text,
	"date_agrement_provisoire" timestamp,
	"duree_annee_psla" integer,
	"organisme_agrement_id" integer,
	"previ_agrement" timestamp,
	"date_depot_dossier_agrement" timestamp,
	"date_reception_agrement" timestamp,
	"date_decision_agrement" timestamp,
	"date_convention_engagement_reciproque" timestamp,
	"cff_fi_client" timestamp,
	"banque_operateur_id" integer,
	"banque_operateur_date" timestamp,
	"banque_client_id" integer,
	"banque_client_date" timestamp,
	"organisme_garantie_emprunt_id" integer,
	"date_deliberation_garantie" timestamp,
	"num_bureau_garantie" text,
	"num_convention_garantie" text,
	"date_signature_garant" timestamp,
	"garantie_emprunt_action_date" timestamp,
	"garantie_emprunt_action_type_id" integer,
	"banque_action_date" timestamp,
	"banque_action_type_id" integer,
	"date_info_annuelle" timestamp,
	"date_info_fin" timestamp,
	"fin_suivi" boolean,
	"commentaire" text,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "reduc_gfa" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reduc_gfa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gfa_id" integer,
	"montant" numeric,
	"date_reduc" timestamp,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "remboursement_anticipe" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "remboursement_anticipe_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"financement_id" integer,
	"numero" integer,
	"montant" numeric,
	"date" timestamp,
	"nb_logt" integer,
	"commentaire" text
);
--> statement-breakpoint
CREATE TABLE "statut_apport" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "statut_apport_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "statut_apport_promoteur_gfa" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "statut_apport_promoteur_gfa_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "statut_cout_mandat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "statut_cout_mandat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "statut_part_sociale" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "statut_part_sociale_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "type_financement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_financement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"categorie" text
);
--> statement-breakpoint
CREATE TABLE "type_mission_budget_architecte" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_mission_budget_architecte_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "usage_frais" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usage_frais_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_prev_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_prev_vefa_reduit" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_prev_vefa" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_prev_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_prev_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_actua" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "caht_reel" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "subv_prev_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "subv_prev_vefa_reduit" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "subv_prev_vefa_normal" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "subv_prev_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "hono_comm_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "hono_comm_vefa_reduit" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "hono_comm_vefa_normal" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "hono_comm_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_prev_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_prev_vefa" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_prev_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_prev_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_reel_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_reel_vefa" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_reel_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "cout_reel_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "quote_part_psla" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "quote_part_vefa_reduit" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "quote_part_vefa_normal" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "quote_part_autre" numeric;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "quote_part_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "mode_repart_quote_part_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "nb_lvo_prev" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "nb_lvo_prev_annee" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_budget_date" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_budget_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_actua_date" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_actua_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_consomme_date" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_consomme_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_reel_date" timestamp;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "frais_reel_commentaire" text;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "liste_budget_frais_stade_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "type_mission_budget_architecte_id" integer;--> statement-breakpoint
ALTER TABLE "tranche" ADD COLUMN "date_contrat_architecte" timestamp;--> statement-breakpoint
ALTER TABLE "budget" ADD CONSTRAINT "budget_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "budget" ADD CONSTRAINT "budget_liste_budget_id_liste_budget_id_fk" FOREIGN KEY ("liste_budget_id") REFERENCES "public"."liste_budget"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "categorie_frais" ADD CONSTRAINT "categorie_frais_usage_frais_id_usage_frais_id_fk" FOREIGN KEY ("usage_frais_id") REFERENCES "public"."usage_frais"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deblocage_psla" ADD CONSTRAINT "deblocage_psla_financement_id_financement_id_fk" FOREIGN KEY ("financement_id") REFERENCES "public"."financement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deblocage_psla" ADD CONSTRAINT "deblocage_psla_psla_id_psla_id_fk" FOREIGN KEY ("psla_id") REFERENCES "public"."psla"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "deblocage_subvention" ADD CONSTRAINT "deblocage_subvention_subvention_id_subvention_id_fk" FOREIGN KEY ("subvention_id") REFERENCES "public"."subvention"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_type_financement_id_type_financement_id_fk" FOREIGN KEY ("type_financement_id") REFERENCES "public"."type_financement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_banque_id_banque_id_fk" FOREIGN KEY ("banque_id") REFERENCES "public"."banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_action_alerte_id_action_alerte_id_fk" FOREIGN KEY ("action_alerte_id") REFERENCES "public"."action_alerte"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_fin_pret_id_fin_pret_id_fk" FOREIGN KEY ("fin_pret_id") REFERENCES "public"."fin_pret"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_index_taux_id_index_taux_id_fk" FOREIGN KEY ("index_taux_id") REFERENCES "public"."index_taux"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_statut_part_sociale_id_statut_part_sociale_id_fk" FOREIGN KEY ("statut_part_sociale_id") REFERENCES "public"."statut_part_sociale"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_statut_apport_id_statut_apport_id_fk" FOREIGN KEY ("statut_apport_id") REFERENCES "public"."statut_apport"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_mandat_hypothequer_id_mandat_hypothequer_id_fk" FOREIGN KEY ("mandat_hypothequer_id") REFERENCES "public"."mandat_hypothequer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "financement" ADD CONSTRAINT "financement_statut_cout_mandat_id_statut_cout_mandat_id_fk" FOREIGN KEY ("statut_cout_mandat_id") REFERENCES "public"."statut_cout_mandat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frais_financier" ADD CONSTRAINT "frais_financier_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "frais_financier" ADD CONSTRAINT "frais_financier_categorie_frais_id_categorie_frais_id_fk" FOREIGN KEY ("categorie_frais_id") REFERENCES "public"."categorie_frais"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gfa" ADD CONSTRAINT "gfa_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gfa" ADD CONSTRAINT "gfa_banque_id_banque_id_fk" FOREIGN KEY ("banque_id") REFERENCES "public"."banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gfa" ADD CONSTRAINT "gfa_statut_apport_promoteur_gfa_id_statut_apport_promoteur_gfa_id_fk" FOREIGN KEY ("statut_apport_promoteur_gfa_id") REFERENCES "public"."statut_apport_promoteur_gfa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gfa" ADD CONSTRAINT "gfa_action_fin_type_id_action_fin_gfa_type_id_fk" FOREIGN KEY ("action_fin_type_id") REFERENCES "public"."action_fin_gfa_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gfa" ADD CONSTRAINT "gfa_periode_taux_gfa_id_periode_taux_gfa_id_fk" FOREIGN KEY ("periode_taux_gfa_id") REFERENCES "public"."periode_taux_gfa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_organisme_agrement_id_organisme_agrement_id_fk" FOREIGN KEY ("organisme_agrement_id") REFERENCES "public"."organisme_agrement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_banque_operateur_id_banque_id_fk" FOREIGN KEY ("banque_operateur_id") REFERENCES "public"."banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_banque_client_id_banque_id_fk" FOREIGN KEY ("banque_client_id") REFERENCES "public"."banque"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_organisme_garantie_emprunt_id_organisme_garantie_emprunt_id_fk" FOREIGN KEY ("organisme_garantie_emprunt_id") REFERENCES "public"."organisme_garantie_emprunt"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_garantie_emprunt_action_type_id_garantie_emprunt_action_type_id_fk" FOREIGN KEY ("garantie_emprunt_action_type_id") REFERENCES "public"."garantie_emprunt_action_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "psla" ADD CONSTRAINT "psla_banque_action_type_id_banque_action_type_id_fk" FOREIGN KEY ("banque_action_type_id") REFERENCES "public"."banque_action_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reduc_gfa" ADD CONSTRAINT "reduc_gfa_gfa_id_gfa_id_fk" FOREIGN KEY ("gfa_id") REFERENCES "public"."gfa"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "remboursement_anticipe" ADD CONSTRAINT "remboursement_anticipe_financement_id_financement_id_fk" FOREIGN KEY ("financement_id") REFERENCES "public"."financement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_mode_repart_quote_part_id_mode_repart_quote_part_id_fk" FOREIGN KEY ("mode_repart_quote_part_id") REFERENCES "public"."mode_repart_quote_part"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_liste_budget_frais_stade_id_liste_budget_id_fk" FOREIGN KEY ("liste_budget_frais_stade_id") REFERENCES "public"."liste_budget"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tranche" ADD CONSTRAINT "tranche_type_mission_budget_architecte_id_type_mission_budget_architecte_id_fk" FOREIGN KEY ("type_mission_budget_architecte_id") REFERENCES "public"."type_mission_budget_architecte"("id") ON DELETE no action ON UPDATE no action;