CREATE TABLE "bilan_caht" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bilan_caht_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer NOT NULL,
	"annee" integer,
	"caht_vefa" numeric,
	"caht_lv_psla" numeric,
	"caht_loyers" numeric,
	"caht_tma" numeric,
	"caht_terrain" numeric,
	"caht_autres" numeric,
	"caht_commentaire" text,
	"nb_lot_vefa" integer,
	"nb_lot_lv_psla" integer,
	"nb_lot_autre" integer,
	"nb_lot_commentaire" text
);
--> statement-breakpoint
CREATE TABLE "bilan_resultat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bilan_resultat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer NOT NULL,
	"annee" integer,
	"result_cpta_sccv_total" numeric,
	"ran_sccv" numeric,
	"cpte_courant_sccv" numeric,
	"date_pvag" timestamp,
	"result_acompte_montant" numeric,
	"result_acompte_date_versement" timestamp,
	"reintegration_fiscale_sccv" numeric,
	"deduction_fiscale_sccv" numeric,
	"reintegration_fiscale_comm" text,
	"deduction_fiscale_comm" text,
	"result_cpta_sccv_is" numeric,
	"result_cpta_sccv_non_is" numeric,
	"reint_hf_result_fiscal" numeric,
	"deduc_hf_perte_fiscale" numeric,
	"reint_hf_perte_comptable" numeric,
	"deduc_hf_result_comptable" numeric,
	"pourc_hf_annee" real,
	"commentaire_pourc_hf" text,
	"result_fisca_sccv_is" numeric,
	"result_fisca_sccv_non_is" numeric,
	"ran_sccv_is" numeric,
	"ran_sccv_non_is" numeric,
	"ran_sccv_total" numeric,
	"quote_part_hf_ran_is" numeric,
	"quote_part_hf_ran_non_is" numeric,
	"quote_part_hf_ran_total" numeric
);
--> statement-breakpoint
CREATE TABLE "bilan_stock" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bilan_stock_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"structure_juridique_id" integer NOT NULL,
	"annee" integer,
	"stock_total_debit_33a35" numeric,
	"stock_total_credit_33a35" numeric,
	"stock_credit_713300" numeric,
	"stock_psla_phase_loc_nb" integer,
	"stock_psla_phase_loc_cout" numeric,
	"stock_invendu_nb" integer,
	"stock_invendu_cout" numeric
);
--> statement-breakpoint
ALTER TABLE "bilan_caht" ADD CONSTRAINT "bilan_caht_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bilan_resultat" ADD CONSTRAINT "bilan_resultat_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "bilan_stock" ADD CONSTRAINT "bilan_stock_structure_juridique_id_structure_juridique_id_fk" FOREIGN KEY ("structure_juridique_id") REFERENCES "public"."structure_juridique"("id") ON DELETE no action ON UPDATE no action;