CREATE TABLE "accord_cadre_assurance" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "accord_cadre_assurance_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"code" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assurance_do_mrh" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assurance_do_mrh_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"num_contrat" text,
	"type_contrat" text,
	"date_souscription" timestamp,
	"date_dgd" timestamp,
	"date_resiliation" timestamp,
	"date_fin_trc" timestamp,
	"accord_cadre" text,
	"cout_operation" numeric,
	"montant_cotisation" numeric,
	"commentaire" text,
	"sur_ope" boolean
);
--> statement-breakpoint
CREATE TABLE "declaration_940" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "declaration_940_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"date_940" timestamp,
	"stock_logt_dat" integer,
	"date_tva_lasm" timestamp,
	"sur_ope" boolean,
	"fin_suivi" boolean,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "sga" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sga_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"num_fiche" integer,
	"est_psla" boolean,
	"date_creation" timestamp,
	"date_sortie" timestamp,
	"prix_terrain_ht" numeric,
	"prix_frais_annexe_ht" numeric,
	"prix_revient_budget" numeric,
	"prix_vente_budget" numeric,
	"liste_budget_id" integer,
	"commentaire" text,
	"surface_utile" real
);
--> statement-breakpoint
ALTER TABLE "assurance_do_mrh" ADD CONSTRAINT "assurance_do_mrh_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "declaration_940" ADD CONSTRAINT "declaration_940_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sga" ADD CONSTRAINT "sga_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sga" ADD CONSTRAINT "sga_liste_budget_id_liste_budget_id_fk" FOREIGN KEY ("liste_budget_id") REFERENCES "public"."liste_budget"("id") ON DELETE no action ON UPDATE no action;