CREATE TABLE "grille_facturation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "grille_facturation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"mission_id" integer NOT NULL,
	"liste_avancement_id" integer,
	"pourcentage" real,
	"montant" numeric
);
--> statement-breakpoint
CREATE TABLE "hono_comm_facture" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hono_comm_facture_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"num_facture" integer,
	"date_facture" timestamp,
	"nb_cla" integer,
	"montant_cla" numeric,
	"nb_levee_option" integer,
	"montant_levee_option" numeric,
	"nb_resa" integer,
	"montant_resa" numeric,
	"nb_acte" integer,
	"montant_acte" numeric,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "hono_comm_nature_achat" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "hono_comm_nature_achat_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"nature_achat_id" integer,
	"montant_cla" numeric,
	"montant_levee_option" numeric,
	"montant_resa" numeric,
	"montant_acte" numeric,
	"pourcentage_resa" real,
	"pourcentage_acte" real,
	"commentaires" text
);
--> statement-breakpoint
CREATE TABLE "mission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tranche_id" integer NOT NULL,
	"date_convention" timestamp,
	"base_hono_unitaire_ht" numeric,
	"base_hono_ht" numeric,
	"type_mission_id" integer,
	"prestataire_id" integer,
	"fin_facturation" boolean,
	"commentaire" text,
	"ordre" integer,
	"nb_mois" integer,
	"nb_logement" integer
);
--> statement-breakpoint
CREATE TABLE "prestataire" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prestataire_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"afficher_mission" boolean
);
--> statement-breakpoint
CREATE TABLE "type_mission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_mission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "liste_avancement" ADD COLUMN "avec_hono_gestion" boolean;--> statement-breakpoint
ALTER TABLE "liste_avancement" ADD COLUMN "pourcentage_standard" real;--> statement-breakpoint
ALTER TABLE "grille_facturation" ADD CONSTRAINT "grille_facturation_mission_id_mission_id_fk" FOREIGN KEY ("mission_id") REFERENCES "public"."mission"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "grille_facturation" ADD CONSTRAINT "grille_facturation_liste_avancement_id_liste_avancement_id_fk" FOREIGN KEY ("liste_avancement_id") REFERENCES "public"."liste_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hono_comm_facture" ADD CONSTRAINT "hono_comm_facture_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hono_comm_nature_achat" ADD CONSTRAINT "hono_comm_nature_achat_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hono_comm_nature_achat" ADD CONSTRAINT "hono_comm_nature_achat_nature_achat_id_nature_achat_id_fk" FOREIGN KEY ("nature_achat_id") REFERENCES "public"."nature_achat"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mission" ADD CONSTRAINT "mission_tranche_id_tranche_id_fk" FOREIGN KEY ("tranche_id") REFERENCES "public"."tranche"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mission" ADD CONSTRAINT "mission_type_mission_id_type_mission_id_fk" FOREIGN KEY ("type_mission_id") REFERENCES "public"."type_mission"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "mission" ADD CONSTRAINT "mission_prestataire_id_prestataire_id_fk" FOREIGN KEY ("prestataire_id") REFERENCES "public"."prestataire"("id") ON DELETE no action ON UPDATE no action;