CREATE TABLE "facture" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facture_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stade_avancement_id" integer NOT NULL,
	"type_mission_id" integer,
	"num_facture" integer,
	"date_facture" timestamp,
	"partiel" boolean,
	"montant_ht" numeric,
	"nb_mois" integer,
	"commentaire" text
);
--> statement-breakpoint
ALTER TABLE "facture" ADD CONSTRAINT "facture_stade_avancement_id_stade_avancement_id_fk" FOREIGN KEY ("stade_avancement_id") REFERENCES "public"."stade_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facture" ADD CONSTRAINT "facture_type_mission_id_type_mission_id_fk" FOREIGN KEY ("type_mission_id") REFERENCES "public"."type_mission"("id") ON DELETE no action ON UPDATE no action;