CREATE TABLE "reserve" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reserve_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lot_id" integer NOT NULL,
	"code" text,
	"type_id" integer,
	"piece_id" integer,
	"entreprise_id" integer,
	"travaux_effectues" boolean,
	"reserve" text,
	"date_reclamation" timestamp,
	"date_intervention" timestamp,
	"envoyer_mail" boolean,
	"envoyer_mail_date" timestamp,
	"est_verrouille" boolean,
	"id_air_bat" integer
);
--> statement-breakpoint
CREATE TABLE "reserve_entreprise" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reserve_entreprise_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"rs" text NOT NULL,
	"adresse1" text,
	"adresse2" text,
	"cp" text,
	"commune" text,
	"telephone" text,
	"fax" text,
	"contact" text,
	"tel_contact" text,
	"corps_etat" text,
	"email" text
);
--> statement-breakpoint
CREATE TABLE "reserve_piece" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reserve_piece_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "reserve_type" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reserve_type_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "reserve" ADD CONSTRAINT "reserve_lot_id_lot_id_fk" FOREIGN KEY ("lot_id") REFERENCES "public"."lot"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reserve" ADD CONSTRAINT "reserve_type_id_reserve_type_id_fk" FOREIGN KEY ("type_id") REFERENCES "public"."reserve_type"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reserve" ADD CONSTRAINT "reserve_piece_id_reserve_piece_id_fk" FOREIGN KEY ("piece_id") REFERENCES "public"."reserve_piece"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reserve" ADD CONSTRAINT "reserve_entreprise_id_reserve_entreprise_id_fk" FOREIGN KEY ("entreprise_id") REFERENCES "public"."reserve_entreprise"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "reserve_lot_id_idx" ON "reserve" USING btree ("lot_id");