CREATE TABLE "droit" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "droit_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"fenetre" text NOT NULL,
	"controle" text NOT NULL,
	"indice" integer,
	"service" text NOT NULL,
	"type" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "commercialisation" ADD COLUMN "prestataire_comm1_id" integer;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD COLUMN "prestataire_comm2_id" integer;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_prestataire_comm1_id_prestataire_id_fk" FOREIGN KEY ("prestataire_comm1_id") REFERENCES "public"."prestataire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "commercialisation" ADD CONSTRAINT "commercialisation_prestataire_comm2_id_prestataire_id_fk" FOREIGN KEY ("prestataire_comm2_id") REFERENCES "public"."prestataire"("id") ON DELETE no action ON UPDATE no action;