CREATE TABLE "fonction" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "fonction_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
-- données existantes antérieures à la FK : remises à NULL, repeuplées par db:transform
UPDATE "personne" SET "fonction_id" = NULL;--> statement-breakpoint
ALTER TABLE "personne" ADD CONSTRAINT "personne_fonction_id_fonction_id_fk" FOREIGN KEY ("fonction_id") REFERENCES "public"."fonction"("id") ON DELETE no action ON UPDATE no action;