CREATE TABLE "contentieux" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contentieux_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"operation_id" integer,
	"objet" text,
	"date_debut" timestamp,
	"date_fin" timestamp,
	"avocats" text,
	"commentaires" text
);
--> statement-breakpoint
ALTER TABLE "contentieux" ADD CONSTRAINT "contentieux_operation_id_operation_id_fk" FOREIGN KEY ("operation_id") REFERENCES "public"."operation"("id") ON DELETE no action ON UPDATE no action;