CREATE TABLE "archive_stade_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "archive_stade_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"date_archivage" timestamp,
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "domaine_stade_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "domaine_stade_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "etat_stade_avancement_alerte" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "etat_stade_avancement_alerte_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "modele_mail" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "modele_mail_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL,
	"sujet" text,
	"corps" text,
	"mode_brouillon" boolean,
	"destinataire" text,
	"destinataire_cc" text,
	"destinataire_cci" text
);
--> statement-breakpoint
CREATE TABLE "motif_annulation" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "motif_annulation_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "parametre_valeur" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "parametre_valeur_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"param" text NOT NULL,
	"typ" text,
	"valeur_d" timestamp,
	"valeur_n" real,
	"valeur_t" text,
	"valeur_h" text
);
--> statement-breakpoint
CREATE TABLE "regle_alerte_stade_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "regle_alerte_stade_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_date_1_id" integer,
	"stade_1_id" integer,
	"etat_1_id" integer,
	"type_date_2_id" integer,
	"stade_2_id" integer,
	"etat_2_id" integer,
	"texte_alerte" text
);
--> statement-breakpoint
CREATE TABLE "type_batiment" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_batiment_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "type_batiment_stade" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_batiment_stade_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"type_batiment_id" integer,
	"liste_avancement_id" integer,
	"intervalle_duree_mois" real,
	"intervalle_duree_mois_etage" real
);
--> statement-breakpoint
CREATE TABLE "type_date_stade_avancement" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "type_date_stade_avancement_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "zonage_abc" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "zonage_abc_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_type_date_1_id_type_date_stade_avancement_id_fk" FOREIGN KEY ("type_date_1_id") REFERENCES "public"."type_date_stade_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_stade_1_id_liste_avancement_id_fk" FOREIGN KEY ("stade_1_id") REFERENCES "public"."liste_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_etat_1_id_etat_stade_avancement_alerte_id_fk" FOREIGN KEY ("etat_1_id") REFERENCES "public"."etat_stade_avancement_alerte"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_type_date_2_id_type_date_stade_avancement_id_fk" FOREIGN KEY ("type_date_2_id") REFERENCES "public"."type_date_stade_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_stade_2_id_liste_avancement_id_fk" FOREIGN KEY ("stade_2_id") REFERENCES "public"."liste_avancement"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "regle_alerte_stade_avancement" ADD CONSTRAINT "regle_alerte_stade_avancement_etat_2_id_etat_stade_avancement_alerte_id_fk" FOREIGN KEY ("etat_2_id") REFERENCES "public"."etat_stade_avancement_alerte"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "type_batiment_stade" ADD CONSTRAINT "type_batiment_stade_type_batiment_id_type_batiment_id_fk" FOREIGN KEY ("type_batiment_id") REFERENCES "public"."type_batiment"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "type_batiment_stade" ADD CONSTRAINT "type_batiment_stade_liste_avancement_id_liste_avancement_id_fk" FOREIGN KEY ("liste_avancement_id") REFERENCES "public"."liste_avancement"("id") ON DELETE no action ON UPDATE no action;