CREATE TABLE "bareme_hono_comm" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bareme_hono_comm_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"libelle" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "hono_comm_facture" ADD COLUMN "prestataire_id" integer;--> statement-breakpoint
ALTER TABLE "hono_comm_facture" ADD COLUMN "bareme_hono_comm_id" integer;--> statement-breakpoint
ALTER TABLE "hono_comm_facture" ADD CONSTRAINT "hono_comm_facture_prestataire_id_prestataire_id_fk" FOREIGN KEY ("prestataire_id") REFERENCES "public"."prestataire"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "hono_comm_facture" ADD CONSTRAINT "hono_comm_facture_bareme_hono_comm_id_bareme_hono_comm_id_fk" FOREIGN KEY ("bareme_hono_comm_id") REFERENCES "public"."bareme_hono_comm"("id") ON DELETE no action ON UPDATE no action;