/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedTicketsRouteImport } from './routes/_authed/tickets'
import { Route as AuthedSccvRouteImport } from './routes/_authed/sccv'
import { Route as AuthedSavRouteImport } from './routes/_authed/sav'
import { Route as AuthedParametresRouteImport } from './routes/_authed/parametres'
import { Route as AuthedOperationsRouteImport } from './routes/_authed/operations'
import { Route as AuthedNouveautesRouteImport } from './routes/_authed/nouveautes'
import { Route as AuthedHonorairesRouteImport } from './routes/_authed/honoraires'
import { Route as AuthedDeclarationsRouteImport } from './routes/_authed/declarations'
import { Route as AuthedComptaRouteImport } from './routes/_authed/compta'
import { Route as AuthedCommercialisationRouteImport } from './routes/_authed/commercialisation'
import { Route as AuthedBilanRouteImport } from './routes/_authed/bilan'
import { Route as AuthedAcquereursRouteImport } from './routes/_authed/acquereurs'
import { Route as AuthedModuleRouteImport } from './routes/_authed/$module'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminMiroirRouteImport } from './routes/_authed/admin/miroir'
import { Route as AuthedAdminImportRouteImport } from './routes/_authed/admin/import'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTicketsRoute = AuthedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSccvRoute = AuthedSccvRouteImport.update({
  id: '/sccv',
  path: '/sccv',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSavRoute = AuthedSavRouteImport.update({
  id: '/sav',
  path: '/sav',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedParametresRoute = AuthedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNouveautesRoute = AuthedNouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedHonorairesRoute = AuthedHonorairesRouteImport.update({
  id: '/honoraires',
  path: '/honoraires',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDeclarationsRoute = AuthedDeclarationsRouteImport.update({
  id: '/declarations',
  path: '/declarations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptaRoute = AuthedComptaRouteImport.update({
  id: '/compta',
  path: '/compta',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommercialisationRoute = AuthedCommercialisationRouteImport.update({
  id: '/commercialisation',
  path: '/commercialisation',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBilanRoute = AuthedBilanRouteImport.update({
  id: '/bilan',
  path: '/bilan',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAcquereursRoute = AuthedAcquereursRouteImport.update({
  id: '/acquereurs',
  path: '/acquereurs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModuleRoute = AuthedModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminMiroirRoute = AuthedAdminMiroirRouteImport.update({
  id: '/admin/miroir',
  path: '/admin/miroir',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminImportRoute = AuthedAdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/$module': typeof AuthedModuleRoute
  '/acquereurs': typeof AuthedAcquereursRoute
  '/bilan': typeof AuthedBilanRoute
  '/commercialisation': typeof AuthedCommercialisationRoute
  '/compta': typeof AuthedComptaRoute
  '/declarations': typeof AuthedDeclarationsRoute
  '/honoraires': typeof AuthedHonorairesRoute
  '/nouveautes': typeof AuthedNouveautesRoute
  '/operations': typeof AuthedOperationsRoute
  '/parametres': typeof AuthedParametresRoute
  '/sav': typeof AuthedSavRoute
  '/sccv': typeof AuthedSccvRoute
  '/tickets': typeof AuthedTicketsRoute
  '/admin/import': typeof AuthedAdminImportRoute
  '/admin/miroir': typeof AuthedAdminMiroirRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$module': typeof AuthedModuleRoute
  '/acquereurs': typeof AuthedAcquereursRoute
  '/bilan': typeof AuthedBilanRoute
  '/commercialisation': typeof AuthedCommercialisationRoute
  '/compta': typeof AuthedComptaRoute
  '/declarations': typeof AuthedDeclarationsRoute
  '/honoraires': typeof AuthedHonorairesRoute
  '/nouveautes': typeof AuthedNouveautesRoute
  '/operations': typeof AuthedOperationsRoute
  '/parametres': typeof AuthedParametresRoute
  '/sav': typeof AuthedSavRoute
  '/sccv': typeof AuthedSccvRoute
  '/tickets': typeof AuthedTicketsRoute
  '/': typeof AuthedIndexRoute
  '/admin/import': typeof AuthedAdminImportRoute
  '/admin/miroir': typeof AuthedAdminMiroirRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$module': typeof AuthedModuleRoute
  '/_authed/acquereurs': typeof AuthedAcquereursRoute
  '/_authed/bilan': typeof AuthedBilanRoute
  '/_authed/commercialisation': typeof AuthedCommercialisationRoute
  '/_authed/compta': typeof AuthedComptaRoute
  '/_authed/declarations': typeof AuthedDeclarationsRoute
  '/_authed/honoraires': typeof AuthedHonorairesRoute
  '/_authed/nouveautes': typeof AuthedNouveautesRoute
  '/_authed/operations': typeof AuthedOperationsRoute
  '/_authed/parametres': typeof AuthedParametresRoute
  '/_authed/sav': typeof AuthedSavRoute
  '/_authed/sccv': typeof AuthedSccvRoute
  '/_authed/tickets': typeof AuthedTicketsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/import': typeof AuthedAdminImportRoute
  '/_authed/admin/miroir': typeof AuthedAdminMiroirRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$module'
    | '/acquereurs'
    | '/bilan'
    | '/commercialisation'
    | '/compta'
    | '/declarations'
    | '/honoraires'
    | '/nouveautes'
    | '/operations'
    | '/parametres'
    | '/sav'
    | '/sccv'
    | '/tickets'
    | '/admin/import'
    | '/admin/miroir'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$module'
    | '/acquereurs'
    | '/bilan'
    | '/commercialisation'
    | '/compta'
    | '/declarations'
    | '/honoraires'
    | '/nouveautes'
    | '/operations'
    | '/parametres'
    | '/sav'
    | '/sccv'
    | '/tickets'
    | '/'
    | '/admin/import'
    | '/admin/miroir'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/$module'
    | '/_authed/acquereurs'
    | '/_authed/bilan'
    | '/_authed/commercialisation'
    | '/_authed/compta'
    | '/_authed/declarations'
    | '/_authed/honoraires'
    | '/_authed/nouveautes'
    | '/_authed/operations'
    | '/_authed/parametres'
    | '/_authed/sav'
    | '/_authed/sccv'
    | '/_authed/tickets'
    | '/_authed/'
    | '/_authed/admin/import'
    | '/_authed/admin/miroir'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/tickets': {
      id: '/_authed/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthedTicketsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sccv': {
      id: '/_authed/sccv'
      path: '/sccv'
      fullPath: '/sccv'
      preLoaderRoute: typeof AuthedSccvRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/sav': {
      id: '/_authed/sav'
      path: '/sav'
      fullPath: '/sav'
      preLoaderRoute: typeof AuthedSavRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/parametres': {
      id: '/_authed/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthedParametresRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/nouveautes': {
      id: '/_authed/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof AuthedNouveautesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/honoraires': {
      id: '/_authed/honoraires'
      path: '/honoraires'
      fullPath: '/honoraires'
      preLoaderRoute: typeof AuthedHonorairesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/declarations': {
      id: '/_authed/declarations'
      path: '/declarations'
      fullPath: '/declarations'
      preLoaderRoute: typeof AuthedDeclarationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compta': {
      id: '/_authed/compta'
      path: '/compta'
      fullPath: '/compta'
      preLoaderRoute: typeof AuthedComptaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/commercialisation': {
      id: '/_authed/commercialisation'
      path: '/commercialisation'
      fullPath: '/commercialisation'
      preLoaderRoute: typeof AuthedCommercialisationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/bilan': {
      id: '/_authed/bilan'
      path: '/bilan'
      fullPath: '/bilan'
      preLoaderRoute: typeof AuthedBilanRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/acquereurs': {
      id: '/_authed/acquereurs'
      path: '/acquereurs'
      fullPath: '/acquereurs'
      preLoaderRoute: typeof AuthedAcquereursRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$module': {
      id: '/_authed/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof AuthedModuleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/miroir': {
      id: '/_authed/admin/miroir'
      path: '/admin/miroir'
      fullPath: '/admin/miroir'
      preLoaderRoute: typeof AuthedAdminMiroirRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/import': {
      id: '/_authed/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthedAdminImportRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedModuleRoute: typeof AuthedModuleRoute
  AuthedAcquereursRoute: typeof AuthedAcquereursRoute
  AuthedBilanRoute: typeof AuthedBilanRoute
  AuthedCommercialisationRoute: typeof AuthedCommercialisationRoute
  AuthedComptaRoute: typeof AuthedComptaRoute
  AuthedDeclarationsRoute: typeof AuthedDeclarationsRoute
  AuthedHonorairesRoute: typeof AuthedHonorairesRoute
  AuthedNouveautesRoute: typeof AuthedNouveautesRoute
  AuthedOperationsRoute: typeof AuthedOperationsRoute
  AuthedParametresRoute: typeof AuthedParametresRoute
  AuthedSavRoute: typeof AuthedSavRoute
  AuthedSccvRoute: typeof AuthedSccvRoute
  AuthedTicketsRoute: typeof AuthedTicketsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminImportRoute: typeof AuthedAdminImportRoute
  AuthedAdminMiroirRoute: typeof AuthedAdminMiroirRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedModuleRoute: AuthedModuleRoute,
  AuthedAcquereursRoute: AuthedAcquereursRoute,
  AuthedBilanRoute: AuthedBilanRoute,
  AuthedCommercialisationRoute: AuthedCommercialisationRoute,
  AuthedComptaRoute: AuthedComptaRoute,
  AuthedDeclarationsRoute: AuthedDeclarationsRoute,
  AuthedHonorairesRoute: AuthedHonorairesRoute,
  AuthedNouveautesRoute: AuthedNouveautesRoute,
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedParametresRoute: AuthedParametresRoute,
  AuthedSavRoute: AuthedSavRoute,
  AuthedSccvRoute: AuthedSccvRoute,
  AuthedTicketsRoute: AuthedTicketsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminImportRoute: AuthedAdminImportRoute,
  AuthedAdminMiroirRoute: AuthedAdminMiroirRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
