/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedOperationsRouteImport } from './routes/_authed/operations'
import { Route as AuthedComptaRouteImport } from './routes/_authed/compta'
import { Route as AuthedCommercialisationRouteImport } from './routes/_authed/commercialisation'
import { Route as AuthedAcquereursRouteImport } from './routes/_authed/acquereurs'
import { Route as AuthedModuleRouteImport } from './routes/_authed/$module'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedAdminImportRouteImport } from './routes/_authed/admin/import'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOperationsRoute = AuthedOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedComptaRoute = AuthedComptaRouteImport.update({
  id: '/compta',
  path: '/compta',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCommercialisationRoute = AuthedCommercialisationRouteImport.update({
  id: '/commercialisation',
  path: '/commercialisation',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAcquereursRoute = AuthedAcquereursRouteImport.update({
  id: '/acquereurs',
  path: '/acquereurs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedModuleRoute = AuthedModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminImportRoute = AuthedAdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/$module': typeof AuthedModuleRoute
  '/acquereurs': typeof AuthedAcquereursRoute
  '/commercialisation': typeof AuthedCommercialisationRoute
  '/compta': typeof AuthedComptaRoute
  '/operations': typeof AuthedOperationsRoute
  '/admin/import': typeof AuthedAdminImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$module': typeof AuthedModuleRoute
  '/acquereurs': typeof AuthedAcquereursRoute
  '/commercialisation': typeof AuthedCommercialisationRoute
  '/compta': typeof AuthedComptaRoute
  '/operations': typeof AuthedOperationsRoute
  '/': typeof AuthedIndexRoute
  '/admin/import': typeof AuthedAdminImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/$module': typeof AuthedModuleRoute
  '/_authed/acquereurs': typeof AuthedAcquereursRoute
  '/_authed/commercialisation': typeof AuthedCommercialisationRoute
  '/_authed/compta': typeof AuthedComptaRoute
  '/_authed/operations': typeof AuthedOperationsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/admin/import': typeof AuthedAdminImportRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$module'
    | '/acquereurs'
    | '/commercialisation'
    | '/compta'
    | '/operations'
    | '/admin/import'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$module'
    | '/acquereurs'
    | '/commercialisation'
    | '/compta'
    | '/operations'
    | '/'
    | '/admin/import'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/$module'
    | '/_authed/acquereurs'
    | '/_authed/commercialisation'
    | '/_authed/compta'
    | '/_authed/operations'
    | '/_authed/'
    | '/_authed/admin/import'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/operations': {
      id: '/_authed/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof AuthedOperationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/compta': {
      id: '/_authed/compta'
      path: '/compta'
      fullPath: '/compta'
      preLoaderRoute: typeof AuthedComptaRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/commercialisation': {
      id: '/_authed/commercialisation'
      path: '/commercialisation'
      fullPath: '/commercialisation'
      preLoaderRoute: typeof AuthedCommercialisationRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/acquereurs': {
      id: '/_authed/acquereurs'
      path: '/acquereurs'
      fullPath: '/acquereurs'
      preLoaderRoute: typeof AuthedAcquereursRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/$module': {
      id: '/_authed/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof AuthedModuleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin/import': {
      id: '/_authed/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AuthedAdminImportRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedModuleRoute: typeof AuthedModuleRoute
  AuthedAcquereursRoute: typeof AuthedAcquereursRoute
  AuthedCommercialisationRoute: typeof AuthedCommercialisationRoute
  AuthedComptaRoute: typeof AuthedComptaRoute
  AuthedOperationsRoute: typeof AuthedOperationsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAdminImportRoute: typeof AuthedAdminImportRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedModuleRoute: AuthedModuleRoute,
  AuthedAcquereursRoute: AuthedAcquereursRoute,
  AuthedCommercialisationRoute: AuthedCommercialisationRoute,
  AuthedComptaRoute: AuthedComptaRoute,
  AuthedOperationsRoute: AuthedOperationsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAdminImportRoute: AuthedAdminImportRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
